[Iter1] add services
benderr/gophermart pull request #2
Opened 2023-12-17 18:06 UTC by benderr

2023-12-22 01:28 UTC, capsulated requested changes
В принципе, круто DDD, и вроде всё правильно в этом плане реализовано. Но вот мне сразу бросается в глаза результирующее количество кода. Без DDD программа была бы ~50% меньше. Это, конечно, философский вопрос, можно об этом и на 1-1 пообщаться, даже интересно, если есть желание. Кроме этого, есть и другие небольшие замечания, написал в комментариях.

Если с какими-то не согласен - пиши ответы на замечания или обсудим на звонке, как удобнее.

И почти нет покрытия тестами)))

2023-12-22 01:28 UTC, capsulated commented on .DS_Store
🔥 В .gitignore! =)

2023-12-22 01:28 UTC, capsulated commented on cmd/gophermart/main.go
> +type CustomValidator struct {
Валидатор и в `main` и в `app`, это ок?

И добавь, плиз, кратко в REAMDE.md как используется эта библиотека в проекте

2023-12-22 01:28 UTC, capsulated commented on cmd/gophermart/main.go
> +	e := app.Run(ctx, conf, logger)
В нашем случае, дополнительный слой app не нужен, так как один экземпляр приложения.  Но если он есть, то в `cmd` должен быть только старт приложения и какие-то конфиги. Запуск сервера точно должен быть в app. И логгер, наверное, всё же в app перенести. Тут чтение флагов актуально.

Дополнительный слой нужен в случае, если есть различные запуски приложения, к примеру, в разных режимах. В `cmd` будет несколько файлов - запусков приложения. Или, как в devops треке, в `app` два разных приложения. В треке было две команды запуска приложений (`cmd` - это сокращение от command), хотя можно сделать один вызов двух app

2023-12-22 01:28 UTC, capsulated commented on internal/app/app.go
> +func Run(ctx context.Context, conf *config.Config, logger logger.Logger) *echo.Echo {
Как написал выше, лучше в app стартовать сервер, а тут ошибку возвращать

2023-12-22 01:28 UTC, capsulated commented on internal/app/app.go
> +	userdelivery.NewUserHandlers(publicGroup, userUsecase, sessionManager, logger)
camelCase в названии бы, читать сложновато. В реальной компании, хорошо читаемый код пригодится в будущем как и тебе самому быстрее ориентироваться,  так и другому разработчику

2023-12-22 01:28 UTC, capsulated commented on internal/config/config.go
> +func MustLoad() *Config {
Да и лучше переименовать в New(), так как это конструктор. `MustLoad` немного сбивает с толку

2023-12-22 01:28 UTC, capsulated commented on internal/domain/accrual/usecase/actions.go
> +	//Этот кусок для удобства тестирования
Лучше, конечно, просто расширить accrualUsecase в помощью композиции в самом тесте и заменить метод:
```go
// Аналог extend из других ЯП
type accrualTestUsecase {
    accrualUsecase
}

// Перезаписываем метод CheckOrder
func (a *accrualUsecase) CheckOrder(ctx context.Context, order string) error { ... }
```

В production коде такое нельзя оставлять

2023-12-22 01:28 UTC, capsulated commented on internal/messagebroker/messagebroker.go
В именах пакетов/фалов snake_case используется, также для простоты чтения

2023-12-22 01:28 UTC, capsulated commented on internal/transactor/transactor.go
> +	// тут функцию для работы (могут быть в разных местах)
👀 а это тут ещё нужно?

2023-12-22 01:28 UTC, capsulated commented on internal/utils/order.go
Пакет `utils` это антипаттерн, так как он будет разбухать в процессе разработки. Надо создавать просто дополнительные объекты в пакетах использования, либо создавать независимые пакеты, если необходимо использовать в нескольких пакетах, к примеру MoonValidator, и его покрывать тестами

2023-12-22 01:28 UTC, capsulated commented on internal/utils/password.go
Это можно либо в пакет, где авторизация перенести, либо создать небольшой отдельный пакет PasswordHasher к примеру. 

Судя по коду, для LunaValidator надо создать пакет, а для проверки пароля и хеша функции просто перенести в UserUseCase, без создания отдельного пакета

2023-12-22 01:28 UTC, capsulated commented on internal/.DS_Store
удалить

2023-12-22 01:28 UTC, capsulated commented on internal/domain/orders/delivery/http.go
> +package delivery
А почему `delivery`? )))

2023-12-22 04:41 UTC, benderr commented on cmd/gophermart/main.go
> +type CustomValidator struct {
А я все переносил в app, забыл удалить тут

2023-12-22 04:46 UTC, benderr commented on internal/config/config.go
> +func MustLoad() *Config {
я где то читал что префикс Must используется в том случае если функция может выбрасывать панику и если в этой функции произошла ошибка, то дальнейшая работа приложения не имеет смысла, по этому сделал через Must

2023-12-22 04:49 UTC, benderr commented on internal/domain/accrual/usecase/actions.go
> +	//Этот кусок для удобства тестирования
ну тут не для юнит-тестирования это сделано, а скорее потому что у нас "обрезанный" сервис и не требуется полная реализация функционала, по факту этот кусок нужно просто удалить, что собственно я и сделал сейчас)

2023-12-22 04:50 UTC, benderr commented on internal/messagebroker/messagebroker.go
А у меня не прошли статик-тесты с неймингом пакетов через snake_case, была ошибка что нельзя в имени пакета использовать знать подчеркивания

2023-12-22 04:51 UTC, benderr commented on internal/transactor/transactor.go
> +	// тут функцию для работы (могут быть в разных местах)
копипаста) надо почистить

2023-12-22 04:52 UTC, benderr commented on internal/utils/order.go
то есть, если я назову его ordervalidator то проблема решится?

2023-12-22 05:03 UTC, benderr commented on internal/domain/orders/delivery/http.go
> +package delivery
Смотрел на курсах по golang у Василия Романова из mail.ru
Идея в общем такая, что delivery это способ "доставки" бизнес-логики до потребителей
Тут может быть http/grpc и другие способы

2023-12-22 05:12 UTC, benderr commented on internal/app/app.go
> +	userdelivery.NewUserHandlers(publicGroup, userUsecase, sessionManager, logger)
справедливо)

2023-12-22 18:04 UTC, benderr commented on internal/utils/order.go
поправил

2023-12-22 18:04 UTC, benderr commented on internal/utils/password.go
перенес

2023-12-22 18:22 UTC, benderr commented on cmd/gophermart/main.go
> +	e := app.Run(ctx, conf, logger)
вынес в app

2023-12-25 13:22 UTC, benderr commented on .DS_Store
done

2023-12-25 13:23 UTC, benderr commented on internal/.DS_Store
done

2023-12-25 13:26 UTC, benderr commented on internal/app/app.go
> +func Run(ctx context.Context, conf *config.Config, logger logger.Logger) *echo.Echo {
переделал

2023-12-26 16:17 UTC, capsulated commented on internal/messagebroker/messagebroker.go
Да, нельзя их так называть. Это сделано для того, чтобы имена пакетов не были длинные, и при составном имени хотелось поделить на два пакета))) Статья [тут](https://rakyll.org/style-packages/) - но это просто статья какого-то программиста-блогера, а не официальные go-guidelines. Но выводы из статьи, в любом случае, можно сделать

2023-12-26 17:06 UTC, capsulated approved these changes
Всё отлично 👍

Очень круто, что:
1. Использовал новые подходы (DDD и т.д.)
2. Отличная комуникацировал в процессу разработки
3. Читаемый структуированный код

2023-12-26 17:06 UTC, capsulated commented on internal/transactor/transactor.go
> +func (t *transactorInstance) Within(ctx context.Context, tFunc func(ctx context.Context, tx *sql.Tx) error) error {
О, тот самый знаменитый воркер, объединяющий транзакции))

2023-12-27 08:39 UTC, merged